// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// myRecursFill
CharacterMatrix myRecursFill(CharacterMatrix d);
RcppExport SEXP eurodata_myRecursFill(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterMatrix >::type d(dSEXP);
    __result = Rcpp::wrap(myRecursFill(d));
    return __result;
END_RCPP
}
